apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: inventorit
type: Opaque
stringData:
  POSTGRES_USER: inventorit_user
  POSTGRES_PASSWORD: inventorit_pass_2024
  POSTGRES_DB: inventorit_db
